# frozen_string_literal: true
source "https://rubygems.org"

gem 'activerecord'
gem 'bcrypt'
gem 'faraday-cookie_jar'
gem 'faraday'
gem 'fileutils'
gem 'git', '~> 1.5'
gem 'pastel'
gem 'permessage_deflate'
gem 'pg'
gem 'rake'
gem 'rexml'
gem 'selenium-webdriver'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'sinatra-websocket'
gem 'sinatra'
gem 'tty-spinner'
gem 'puma'
